#!/bin/sh

ssid=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d':' -f2)
ip=$(ip -o route get to 1.1.1.1 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
icon="SSID:"
printf "%s %s ^C6^(%s)^d^" "$icon" "$ssid" "$ip"
