#!/bin/bash

id=8
bat_perc=$(cat /sys/class/power_supply/BAT0/capacity)
bat_status=""

# Check the battery status
if [[ $(cat /sys/class/power_supply/BAT0/status) == "Discharging" ]]; then
  bat_status=""
else
  bat_status="+"
fi 

if [[ $bat_perc -gt 25 ]]; then
    status_color="^C2^"
elif [[ $bat_perc -gt 15 ]]; then
    status_color="^C3^"
else
    status_color="^C1^"
fi

if [[ $bat_status -eq "+" ]]; then
    status_color="^C2^"
fi

icon="BAT:"
echo -e "$status_color$icon $bat_status$bat_perc%^d^"

